### ISSUE TITLE
Update ReadMe File with Proper Content

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/NotesJar#1]
Write a Readme file to describe the application. Before writing the readme file, understand the code flow and use the application. This will give you a better context for the application when writing it.

A better readme consists of:
- Badges - created using [Shields](https://shields.io/) or [Badgen](https://badgen.net/)
- Screenshots of the pages
- Summary of the project
- Installation Guide
- Author details 
- License Information

**Comment by amitsing8576** [comment]
sir can you please assign me this issue under codepeak .

**Comment by arpitghura** [comment]
Sure @amitsing8576, Go ahead.

**Comment by amitsing8576** [comment]
sir where can i get the license information about the project

**Comment by arpitghura** [comment]
> sir where can i get the license information about the project

The project is MIT Licensed. I will update it soon.
