### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by Sami3160** [arpitghura/NotesJar#11]
After adding a note and then deleting it, brings 'no-notes.gif' which is correct..
![no-notes](https://github.com/arpitghura/NotesJar/assets/110652247/d5dae05a-86b1-4856-b391-712756d0544a)
but after adding two or more notes, then after deleting even one of then makes this gif visible. It should be fixed as it says "No Notes Found", but at moment their are some notes present right their.
![Screenshot (71)](https://github.com/arpitghura/NotesJar/assets/110652247/015092f9-18a4-47ad-be51-1fd4e851d460)
Please acknowledge this issue, and assign this to me✌

**Comment by arpitghura** [comment]
Okay @Sami3160 Go ahead.

**Comment by arpitghura** [comment]
#12 resolved this issue.
