### ISSUE TITLE
Add dark mode to the website 

### ISSUE THREAD

**Issue by Preeti8021** [arpitghura/NotesJar#18]
I would like to work on this under CodePeak'23. I will add a button which would perform this action.

**Comment by Preeti8021** [comment]
Please assign this issue to me. @arpitghura

**Comment by A-nirvana** [comment]
If this comes under Dwoc I would love to work on it. Please assign it to me

**Comment by arpitghura** [comment]
Go a head @A-nirvana

**Comment by A-nirvana** [comment]
Do you want me to put everything in the dark theme or the header should not be touched? I asked this because except for the header I've added the dark theme in the main body. And I wish to add more to the improvement of the UI. Should I create an issue? Thanks

**Comment by arpitghura** [comment]
Yes use a slight darker background gradient.

**Comment by A-nirvana** [comment]
Okay I will create a different image for the the logo for the dark theme, and also the Add note note button will be changed. I'll try creating a pull request today itself. My progress has been like this till now
![Screenshot (23)](https://github.com/arpitghura/NotesJar/assets/145558376/6cc5e992-7e50-4ddc-b847-d6a202116452)

**Comment by arpitghura** [comment]
#30 resolved this issue.
