### ISSUE TITLE
Modify Navbar designs

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/NotesJar#3]
The navbar looks bulky. It's better to create a simpler yet useful navbar. It should contain the Logo and button to create the notes. Also, change the background.

**Comment by saurabhgdeshmukh** [comment]
please assign this issue to me.

**Comment by arpitghura** [comment]
Hey @saurabhgdeshmukh welcome to the community. Assigning this issue to you, but remember that you need to implement this design in a new branch to avoid any conflicts.

**Comment by saurabhgdeshmukh** [comment]
can I modify the button and logo or do I have to use the same one?

**Comment by arpitghura** [comment]
Use the same logo

**Comment by saurabhgdeshmukh** [comment]
@arpitghura I have changed the navbar dimensions but what kind of changes do you want in the background?

**Comment by arpitghura** [comment]
You can use simple backgrounds, whether images, gradients, or colors, but the background or the overall navbar looks classy. You can look for some designs on Dribble or Pinterest.

> @arpitghura I have changed the navbar dimensions but what kind of changes do you want in the background?

**Comment by gayathrik23** [comment]
@arpitghura can you assign this issue to me .. under dwoc... i would like to work on it
