### ISSUE TITLE
Add Animations to the create (add new) button

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/NotesJar#4]
Add animations to the 'Add a note' on hover and on click using CSS only.

**Comment by Preeti8021** [comment]
please assign this issue to me ! @arpitghura

**Comment by Srayash** [comment]
Hey, I would like to contribute to this, Please assign this issue to me. 
I'll make the Button grow in size on hovering.

**Comment by Sami3160** [comment]
hello, can you assign this issue to me?😊

**Comment by arpitghura** [comment]
@Preeti8021 it's yours.

**Comment by Preeti8021** [comment]
I have made few changes to the button, kindly review it. If it looks good, I will commit and send pull request. @arpitghura 

https://github.com/arpitghura/NotesJar/assets/103981488/dc7710c4-cb2b-49da-aef6-4d235690ecc3
