### ISSUE TITLE
Need for contribution.md file 

### ISSUE THREAD

**Issue by deveshio** [arpitghura/NotesJar#5]
As your projects don't contain the contribution.md file 
it is getting difficult to get an understanding 
I know the 
steps are provided in readMe.md file 
but it is still better to have a contribution. md file instead of putting the steps in the readme. MD

**Comment by arpitghura** [comment]
okay, go ahead and create a CONTRIBUTING.md file.

**Comment by mdsahilnoob** [comment]
@arpitghura can you please assign this issue to me? I am interested in helping
